spring.application.name=CatalogService
server.port=9001
server.tomcat.connection-timeout=20000
server.tomcat.keep-alive-timeout=15000
server.tomcat.threads.max=50
server.tomcat.threads.min-spare=5

spring.profiles.active=test
